---
language: ruby
matrix:
  fast_finish: true
  include:
    - rvm: 2.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_master.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_master.gemfile

sudo: false

before_install:
  - gem install bundler -v '< 2' --conservative

install: bundle install --without development --retry=3 --jobs=3

script:
  - bundle exec rubocop
  - bundle exec rspec
